### ISSUE TITLE
Wrong ##DATA TYPE for some of the new converter profiles

### ISSUE THREAD

**Issue by herrdivad** [ComPlat/chemotion-converter-app#56]
Hi Team,
Hi @phuang26 

after checking the conversion of the new data formats on https://complat-eln.ioc.kit.edu/ , I found some problems / bugs / issues.

* **SEC** and **AIF** is working but both are using the wrong ##DATA TYPE=CYCLIC VOLTAMMETRY. Maybe they are using and old profile version or the right entry is missing.
* CDS (some kind of csv file) won't be converted at all although I could see the profile in the list.

Thanks for the help and best wishes.

**Comment by StarmanMartin** [comment]
Fix for: SEC and AIF is working but both are using the wrong ##DATA TYPE=CYCLIC VOLTAMMETRY. Maybe they are using and old profile version or the right entry is missing.
 - This is a bug in the profile and can be fixed via the admin converter interface.

Fix for: CDS (some kind of csv file) won't be converted at all although I could see the profile in the list:
 - Fixed CSV new line error
