### ISSUE TITLE
New File format for SEC reader

### ISSUE THREAD

**Issue by StarmanMartin** [ComPlat/chemotion-converter-app#74]
[THF-SEC.TXT](https://github.com/ComPlat/chemotion-converter-app/files/12738219/THF-SEC.TXT)
[DMAC-SEC.TXT](https://github.com/ComPlat/chemotion-converter-app/files/12738221/DMAC-SEC.TXT)

**Comment by herrdivad** [comment]
There are also small updates to the profiles. Now the column counter as identifier is back again. Tested on Standalone Version where it works. Will send the profiles to @phuang26 via Mail
